repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.3.0
  hooks:
  - id: conventional-pre-commit
    stages: [ commit-msg ]
    args: [ feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert ]

- repo: local
  hooks:
  - id: min-commit-length
    name: Check minimum commit message length
    entry: python -c 'import sys; msg = open(sys.argv[1]).read(); sys.exit(1 if len(msg) < 30 else 0)'
    language: python
    stages: [ commit-msg ]
