version: '3'

services:
  workload-scheduler:
    image: python:3.9-slim
    container_name: workload-scheduler
    command: "python src/main.py"
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Paris
      - PYTHONPATH=/app
    restart: unless-stopped
    volumes:
      - ./:/app
      - sqlite-data:/app/data
    working_dir: /app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  # Visualiseur SQLite pour la base de données du scheduler
  sqlite-web:
    image: fizzbuzz2/sqlite-viewer:3.10
    container_name: scheduler-sqlite-viewer
    ports:
      - "8081:8080"
    depends_on:
      - workload-scheduler
    environment:
      - SQLITE_DATABASE=/data/sqlite/scheduler.db
      - TZ=Europe/Paris
    volumes:
      - sqlite-data:/data:rw
    restart: unless-stopped

volumes:
  sqlite-data:

networks:
  default:
    name: workload-scheduler-network
