version: '3'

tasks:

  default:
    desc: List available tasks
    cmds:
    - task --list

  docker:build:
    desc: Build Docker image
    cmds:
    - docker build -t {{.PROJECT_NAME | default .PWD | base}}:latest .

  docker:run:
    desc: Run Docker container
    cmds:
    - docker run --rm -p 8080:8080 {{.PROJECT_NAME | default .PWD | base}}:latest
