version: '3'

vars:
  IMAGE_NAME: fizzbuzz2/workload-scheduler:v2.0.0

tasks:
  build:
    desc: Build Docker image
    cmds:
    - docker compose build --push

  run:
    desc: Run the Docker container
    cmds:
    - docker compose up -d

  show-logs:
    desc: Show logs from the running container
    cmds:
    - docker compose logs -f

  run-dev:
    desc: Run the app localy
    dir: src
    cmds:
    - pipenv run python main.py

  shell:
    desc: Open a shell in the running container
    cmds:
    - pipenv shell

  helm-template:
    desc: template helm chart
    cmds:
    - helm template ./helm

  apply-deployment:
    desc: apply a deployment kubernetes
    cmds:
    - kubectl apply -f tests/deployment.yaml

  coverage-api:
  desc: "Run API unit tests with code coverage"
  cmds:
    - coverage run -m pytest src/tests/test_api.py
    - coverage report -m

coverage-integration:
  desc: "Run integration tests with code coverage"
  cmds:
    - coverage run -m pytest src/tests/test_integration.py
    - coverage report -m

default:
  desc: List available tasks
  cmds:
  - task --list
