version: '3'

vars:
  IMAGE_NAME: fizzbuzz2/portal-checker:v1.7.0

tasks:
  build:
    desc: Build Docker image
    cmds:
    - docker compose build --push

  run:
    desc: Run the Docker container
    cmds:
    - docker compose up -d

default:
  desc: List available tasks
  cmds:
  - task --list
