apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ $.Release.Name | quote }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/router.middlewares: kube-infra-generic-dashboard-auth@kubernetescrd

spec:
  ingressClassName: traefik
  rules:
  - host: {{ $.Values.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            service:
              name:  {{ template "application.fullname" . }}
              port:
                number: {{ $.Values.service.port }}
  tls:
  - hosts:
    - {{ $.Values.domainName }}
    secretName: {{ $.Release.Name }}-certificate-tls
