
services:
    app:
      container_name: workload-scheduler
      image: fizzbuzz2/workload-scheduler:v1.0.3
      ports:
        - "8000:8000"
      build:
        platforms:
          - linux/amd64
          - linux/arm64
        context: . # docker-compose.yml in current directory
      environment:
        - KUBE_ENV=development
      volumes:
        - .:/app