name: Helm Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Install Helm Chart in namespace `workload-scheduler`
        if: steps.list-changed.outputs.changed == 'true'
        run: helm install workload-scheduler ./charts/workload-scheduler --namespace workload-scheduler --create-namespace

      - name: Wait for Pods to be ready in namespace `workload-scheduler`
        if: steps.list-changed.outputs.changed == 'true'
        run: sleep 120
      
      - name: Check Pod status in namespace `workload-scheduler`
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl get pods -n workload-scheduler

      - name: Print logs for a pod with label `app=workload-scheduler`
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl logs -n workload-scheduler -l app=workload-scheduler
      
      - name: Check if workload-scheduler pod is running
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          STATUS=$(kubectl get pods -l app=workload-scheduler -n workload-scheduler -o jsonpath="{.items[*].status.phase}")
          if [ "$STATUS" != "Running" ]; then
            echo "Pod is not in Running state: $STATUS"
            exit 1
          fi
          echo "All pods are in the Running state."
